### ISSUE TITLE
Add command GET in console [feature request]

### ISSUE THREAD

**Issue by papayou66** [FlightOne/FlightOne#191]
Could you add a command to see quicly a variable in console ? 
Thanks

**Comment by Arti3DPlayer** [comment]
provide example please ?

**Comment by papayou66** [comment]
yes example type in console get channel 
you will get all the variables that contains the word channel,

**Comment by Arti3DPlayer** [comment]
@papayou66 I guess better to create autocomplete(dropdown) like in google. But I need @rs2k to help me with this:)

**Comment by Arti3DPlayer** [comment]
Close, because console isn't need anymore
