### ISSUE TITLE
Amperage Draw Telemetry

### ISSUE THREAD

**Issue by mschick2006** [FlightOne/FlightOne#255]
I chatted with Preston Garrison on FB about adding the option in RF1 to return the amperage draw telemetry, from the current sensor in your boards, as a total value consumption rather than a percentage.  He asked me to add this as an issue in here as a reminder to take a look at it.  Thanks!

**Comment by PGIII** [comment]
will add this to the todo list thank you for adding this :)

**Comment by mschick2006** [comment]
No problem!  Thanks for looking into it

Mike Schick

**Comment by PGIII** [comment]
added in 1.1.186
