### ISSUE TITLE
Flight one configurator will not spin motors in opposite directions and quopa mode will not either 

### ISSUE THREAD

**Issue by joshua32crane** [FlightOne/FlightOne#267]
I can not get the dalrc 40amp 32bit 4 in 1 esc to work correctly with raceflight. When I try to do the quopa mode, it will not spin the props the other direction and also in the configurator the motors won't spin to other direction when switching the motor direction. I've tried everything,  please help.

**Comment by PGIII** [comment]
try the latest, the wizards and quopa have been working great on the Bolt32 and Spark32 so sounds like it could related to that specific esc
