### ISSUE TITLE
Please fix Acrolevel

### ISSUE THREAD

**Issue by Pyrolassist** [FlightOne/FlightOne#269]
Acrolevel does not seem to be working. It's handy for beginners and tiny whoop pilots.

**Comment by Pyrolassist** [comment]
585

**Comment by Pyrolassist** [comment]
I have a millivolt v1 and a Revolt v1 both worked fine on RC300 range FW's and I've tried 570 and up. Level works fine and Braindrain works fine

**Comment by PGIII** [comment]
set slp1=2.500
set sli1=0.050
set sla1=40.000
set sld1=0.014
save

try those

**Comment by Pyrolassist** [comment]
Thanks I’ll try those

**Comment by tromax14** [comment]
Hope you find solution!
