### ISSUE TITLE
Profile 3 Issues

### ISSUE THREAD

**Issue by justingoesfpv** [FlightOne/FlightOne#271]
No matter what you do or put in profile 3, expect the howling of a banshee.

**Comment by justingoesfpv** [comment]
No matter what you put on profile 3, you get this:

![profile3](https://user-images.githubusercontent.com/1522581/39057180-9e759cb8-4486-11e8-8955-a806a49ce421.PNG)

**Comment by DJBlackhawk** [comment]
What firmware version are you running and is it still a factor?

**Comment by justingoesfpv** [comment]
Not a factor. This is from months ago. I no longer fly anything Flight One.
