### ISSUE TITLE
Calibrating the Voltage reading

### ISSUE THREAD

**Issue by nksmith4747** [FlightOne/FlightOne#287]
If I use a 4s hv which reads 17.2V with an ISDT battery checker then using a value of 0.566 for voffset set through the cli gives me a value of 17.2V on the configurator and on the Spektrum telemetry.  If I then change to a 4s normal which reads 16.55V on the ISDT it reads  17.13V on the configurator and Spektrum.  The change of 0.65V is not measured linearly therefore when the battery voltage goes down with normal usage you won't know the actual value.  Therefore as it stands it is unusable.  There is probably a clue in the name of the parameter as it is called an offset not a multiplier, but it seems to do a bit of both.
Also the configuration tab of the configurator only allows values between 0.75 and 1.2 even though the popup says 0.5 to 1.5.

**Comment by PGIII** [comment]
The way voltage dividers works means that its going to be accurate at some voltages than others, the offset it a multiplier and it always applied, in general its best to calibrate for lower voltage since its more important that its accurate when your battery is closer to being dead
