### ISSUE TITLE
Spektrum Voltage telemetry is not working.

### ISSUE THREAD

**Issue by neows6** [FlightOne/FlightOne#290]
In summary ever since build 1.1.140 Spektrum Voltage telemetry will appropriately send the voltage upon plugging in the battery, but the voltage does not update during flight.
It will update upon dearm really cycle, but once again will stay static.

All subsequent Flightone FW since has the same issue.
I have updated the FW on the Spektrum SPM4649t.
I have updated my TX to airware 1.20 & 2.0 and it does not change the issue.

**Comment by PGIII** [comment]
Should be fixed in 1.1.190

**Comment by neows6** [comment]
Thank you!

Don
