### ISSUE TITLE
Level and Acrolevel cause motors to ramp up to full throttle 

### ISSUE THREAD

**Issue by mikethetiger** [FlightOne/FlightOne#292]
Using fw 1.1.140 on Skitzo RevoltOSD and Skitzo Bolt32. After arming and switching in either level or acrolevel cause my motors to spin up to just about full throttle. I’ve tried using my Skitzo Revolt v3 and Skitzo Black Bolt 4in1 and different combinations of the stack. Even using different motors, I still get the same behavior from my quad..

**Comment by PGIII** [comment]
Is this with or without props on ?

**Comment by mikethetiger** [comment]
It happens with and without props on.

**Comment by PGIII** [comment]
so is it taking of the ground with props on ? does it fly normally in acro mode

**Comment by mikethetiger** [comment]
It lifts off the ground when props are on and I’m not touching the throttle. It seems to be a problem when I assign acrolevel or level to a switch. If I disable it (toggle off in configurator) and only use acro, it operates normally.

**Comment by DJBlackhawk** [comment]
Level seems to be fine in latest betas, it’s AcroLevel that’s the problem
 https://www.youtube.com/watch?v=gXwbgUinYvM

**Comment by DJBlackhawk** [comment]
AcroLevel is still an issue in 1.1.168 

https://youtu.be/6IuWRqISQNI

**Comment by DJBlackhawk** [comment]
Another user running public 1.1.140 release 

https://www.youtube.com/watch?v=xYtgXZ8sBy8&feature=share

**Comment by mikethetiger** [comment]
I see I’m not the only one with the same issues.

**Comment by PGIII** [comment]
i have made some changes to acro level and level in the latest and changed the default pids for it as well, 1.1.180+, let me know if the issue still persists

**Comment by mikethetiger** [comment]
I updated to 1.1.182 and level mode works flawlessly. Acrolevel, however, is very jittery when it returns to a level position while hovering. I guess I'll use level mode when I come back in for landings. Thanks for the work on  this!!
