### ISSUE TITLE
RevoltOSD doesn't work logging on 1.1.140.184

### ISSUE THREAD

**Issue by dobodzinskiy** [FlightOne/FlightOne#293]
I set logging to switch and tried to write some logs, but at LOGGING tab there is always empty.

**Comment by PGIII** [comment]
Did you format the flash and are you using Dshot or proshot ?

**Comment by dobodzinskiy** [comment]
Hello!
Yes, i've tried both to format and erase the flash. Didn't help. I'm using Dshot600

**Comment by PGIII** [comment]
logging won't work on dshot or proshot try multishot

**Comment by dobodzinskiy** [comment]
Kinda weird, but it works now. Thanks!

**Comment by DJBlackhawk** [comment]
If you test Quopa Mode it may not correctly revert back from pro shot to Multishot thus logging won’t work..
