### ISSUE TITLE
NEw OSD features in 1.68 are Not available in Configurator 149.

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FlightOne#295]
The new OSD features, such as profile and VTX channel are not available to select via the OSD configg page.

**Comment by Arti3DPlayer** [comment]
Did you use 1.1.168 configurator(it still in dev, so you need to install it manually) ?

https://flightone.com/configurator/1.1.168/

**Comment by 2dogrc** [comment]
Got it with that config.
