### ISSUE TITLE
motor twitching when selecting taranis rx3 pin slider in configurator

### ISSUE THREAD

**Issue by BashFPV** [FlightOne/FlightOne#297]
1.168 config / 1.168 firmware.

Default 5inch race set up.  after completing the basic set up process. 

Under configuration  > telemetry.  there is a taranis rx3 turn on/off option for lua to work.

When I slide it to ON position and save.  my bottom right motor starts to twitch/pulse.  If I slide it to OFF. the motor stops twitching/pulsing.  

Multishot.

Revolt v3 / spedix 4-1 30A, / RXSR,

**Comment by PGIII** [comment]
should be fixed in 1.1.181
