### ISSUE TITLE
175 Firmware Motor Spin up When Sport Connected to RX3

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FlightOne#298]
Flashed the new version 175.  On Revolt/Bolt combo.  RX3 is Sport.  Running multishot, with the battery plugged in the one motor twitches and even spun up on me once.  Twitching can start any where from 3-10 seconds after connected.  There is no change when deselecting Frysky Telemetry in the config.

If i desolder the wire from the Revolt, and then select multishot, there are no issues.

**Comment by PGIII** [comment]
should be fixed in 1.1.181
