### ISSUE TITLE
Proshot is DANGEROUS!  Motors spin up uncommaned when disarmed

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FlightOne#300]
When selecting Proshot, any of them, on BL Heli32, some motors twitch and even spin up when quad is disarmed.  I recommend removing these options until they are 100%, its just dangerous.

**Comment by DJBlackhawk** [comment]
Which version are you on? 
Does it happen in Level or Acro mode (no mode selected) or only AcroLevel?

**Comment by 2dogrc** [comment]
Tha was on 1.29and 1.158 I believe. It happened when the quad was not armed and sitting on the table going through the wizards. 

Mark Grohe
2dogrc@gmail.com
682.552.6494
Follow us on Twitter: www.twitter.com/2dogrc
Our YouTube Channel
www.2dogrc.com/2dogrc

**Comment by DJBlackhawk** [comment]
Is this still occurring after beta update 1.1.176?

**Comment by 2dogrc** [comment]
I have not had a chance to try it.

**Comment by PGIII** [comment]
The latest version of Blheli32, 32.6 I believe, is supposed to fix the issue with proshot, I’ve seen similar reports of motors twitching on betaflight as well with proshot and blheli32, i plan on testing the new version this week to see if it does fix the issue

**Comment by DJBlackhawk** [comment]
I noticed subtle twitch and slight motor wind ups but very brief and barely a full revolution with 32bit ESC's on 32.4. I haven't tested Blheli32 firmware 32.6 because PGIII mentioned that 32.6 was still in beta an could impose other bugs or issues?

**Comment by 2dogrc** [comment]
Tested on 32.6, does not spin up.
