### ISSUE TITLE
Frsky Telemetry Not working on 178, or 190

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FlightOne#303]
No Frsky Telemetry on firmware 178 or 190.  Tested on Revolt, with Sport on RX3.  Reflashed to 114 and telemetry worked.

**Comment by PGIII** [comment]
Can you post a dump from the quad, it worked on my test frsky quad when I tried

**Comment by greennuts** [comment]
Hm, just had similar issue on 190. Can't get telemetry to work. Using FX400R RX

**Comment by DJBlackhawk** [comment]
> No Frsky Telemetry on firmware 178 or 190. Tested on Revolt, with Sport on RX3. Reflashed to 114 and telemetry worked.

Is this still an issue on 1.2.64 for you?

**Comment by 2dogrc** [comment]
Not sure, abandoned using Telemetry, used OSD boards instead.
