### ISSUE TITLE
FPORT for frsky receiver

### ISSUE THREAD

**Issue by error414** [FlightOne/FlightOne#307]
Hi,

frsky provides for receivers firmware with Fport support https://www.frsky-rc.com/download/  . By one wire SBUS + SPORT + RSSI. 

Is it possible to add Fport support to F1?

thank you very much.

**Comment by PGIII** [comment]
Yes we plan on adding it

**Comment by error414** [comment]
great, do you know the approximate time?

**Comment by twystidceed** [comment]
any update on this

**Comment by w2fly** [comment]
FPort is now working on FalcoX or not yet?

**Comment by w2fly** [comment]
> 
> 
> Yes we plan on adding it

FPort is now working on FalcoX or not yet?

**Comment by PGIII** [comment]
Yes its been supported in FalcoX since the first public version
