### ISSUE TITLE
Configurator Tab mAH Offset range doesn't match allowable values error

### ISSUE THREAD

**Issue by DJBlackhawk** [FlightOne/FlightOne#313]
Severity low, Priority low: Configurator 1.2.50/Configuration Tab/mAH offset states: States in RED font that Value should be in the range from 0.5 to 1.5 but this will only allow from 0.9 to 1.2 any other value will prompt error message incorrect value.

**Comment by Arti3DPlayer** [comment]
fixed in 1.2.51
