### ISSUE TITLE
Correct Level and AcroLevel PIDs for each preset and each of the three profiles

### ISSUE THREAD

**Issue by DJBlackhawk** [FlightOne/FlightOne#315]
Only 2.5inch and 7 inch 4s PID preset's set slp sli sla sld, also If you save any other preset it saves incorrect values. 

slp1=2.000
set sli1=0.100
set sla1=35.000
set sld1=0.030

slp2=2.000
set sli2=0.100
set sla2=35.000
set sld2=0.030

slp3=2.000
set sli3=0.100
set sla3=35.000
set sld3=0.030

**Comment by PGIII** [comment]
Fixed in latest
