### ISSUE TITLE
Motors spin when armed and throttle not at idle 1.2.64

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FlightOne#318]
Quad arms when throttle is not at idle!
Multishot 1.2.62 and .64, always double arm( also single arm), taranis.  put the throttle a little up, on radio data shows 89%, then double flip the arm switch, and motors spin.
showing 1061 us on the output screen of the Taranis
on single arm as well.

Also if the arm switched is bumped to arm after the battery is plugged in and the throttle is above 1061 us or so and you move the throttle down to idle the motors start.

DFU Flash from 1.2.62, did not import settings.

**Comment by PGIII** [comment]
How far up is your throttle ? It’s a threshold so it will allow a little above completely 0

**Comment by 2dogrc** [comment]
1061 us

Mark Grohe
2dogrc@gmail.com
682.552.6494
Follow us on Twitter: www.twitter.com/2dogrc
Our YouTube Channel
www.2dogrc.com/2dogrc

**Comment by DJBlackhawk** [comment]
I can duplicate and repeat on Spektrum, Taranis but not on Crossfire. Move throttle up to just about any position from full throttle, 3/4, 1/2, 1/4 etc then Single or Double arm and move throttle to idle while arm switch was forgotten in Arm position, motors start to spin. It's more severe if you selected single arm in configurator then flip arm twice while throttle was up and moved down quad will launch! I'm not sure if this is a bug or was meant to work like this? Normally if I forgot throttle up Spektrum will warn me anyway on power on. If I don't turn the transmitter off and forgot throttle slightly up, middle or high and try to arm nothing happens, I typically will realize and disarm then move throttle to idle. Even if I didn't disarm I would be at idle which is not a problem if quad uses double arm. If using Single arm its very dangerous and will launch.

**Comment by DJBlackhawk** [comment]
1.2.64 Make sure you single arm or double arm at least once, Disarm, then move the throttle up to any position, arm then move throttle back down to idle. It's not too crazy on double arm but single arm it's like its bypassing the Saftey feature and motors spin up ramped! It's not what I would consider a normal first-time issue it's only if you're leaving your transmitter on and hot swapping packs you may encounter it.
