### ISSUE TITLE
ESC Idle Speed step not sending signal to Motor #3 when asking if all motors are spinning the proper direction.

### ISSUE THREAD

**Issue by 2dogrc** [FlightOne/FlightOne#319]
Also, on AIkon Bl heli 32 ESC, on the third part of the motor idle step where you click Start All Motors, motor 3 does not get a signal to spin.  I know because my CL racing lights don't go on.   It works on the first 2 steps.

I tried twice.  Once without disconnecting the battery from the Calibrate Motors step prior and once with disconnecting the battery between steps.

DFU Flash from 1.2.62, did not import settings.

**Comment by PGIII** [comment]
Make sure the esc is on at least 32.4 sounds like the bug early BLheli32 versions had with Dshot commands

**Comment by 2dogrc** [comment]
Just checked 32.6.

**Comment by PGIII** [comment]
I haven’t been able to replicate this over multiple quads and versions, as well as on 32.4 and 32.6, make sure to try the latest 1.2.64 or the latest beta
