### ISSUE TITLE
No RC data in MSP package

### ISSUE THREAD

**Issue by artemaminov** [FlightOne/FlightOne#327]
So I can't get in to MWOSD menu with sticks and there is no RSSI data also.
Millivolt v1 using

**Comment by SkeemoFPV** [comment]
Are you using FlightOne or FalcoX ?

**Comment by artemaminov** [comment]
FlightOne 1.2.94.193
Flight One Revolt (Millivolt v1)
MWOSD 1.9.1.4 FW

**Comment by SkeemoFPV** [comment]
Unfortunately what you’re trying to do won’t work, you need to flash a special fw to the OSD board. You will need to join the FlightOne Discord channel if you haven’t already, then look in External OSD topic. Pinned in that section is the FW you need and a set of instructions explaining what you need to do.
https://flightone.com/discord.php

**Comment by artemaminov** [comment]
Flashed ttyosd.
It works, but some characters are corrupted % -> &
![IMG_4013](https://user-images.githubusercontent.com/570305/75922066-1e950c80-5e84-11ea-95e9-ad347ee08fac.jpg)
