### ISSUE TITLE
Falco X betafpv405

### ISSUE THREAD

**Issue by BlueShrimpFPV** [FlightOne/FlightOne#333]
Issue with the license for betafpv405 only two Motors Spinning. Tried everything but no Chance.

**Comment by FloFPV** [comment]
Same Problem...only the lebt two motors..

**Comment by BlueShrimpFPV** [comment]
You closed the Case with No Tipps....the issue ist still there --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 19.10.21, 17:42 schrieb PGIII ***@***.***>:

   
  Closed #333.

**Comment by PGIII** [comment]
If you have a FalcoX related issue please open a issue at https://github.com/FlightOne/FalcoX-Issue-Tracker
